"""empty message

Revision ID: 04c73f7a0b6d
Revises: b61e2b2aa4ed
Create Date: 2024-10-22 22:56:39.812202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c73f7a0b6d'
down_revision = 'b61e2b2aa4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('employment_time')

    # ### end Alembic commands ###
