"""empty message

Revision ID: 09ed484f2268
Revises: 5272575952ec
Create Date: 2024-11-02 20:54:10.299425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ed484f2268'
down_revision = '5272575952ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_column('end')
        batch_op.drop_column('start')

    # ### end Alembic commands ###
