"""empty message

Revision ID: 0d2b46bb97ea
Revises: c862489d7ea9
Create Date: 2024-10-18 21:15:34.941048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d2b46bb97ea'
down_revision = 'c862489d7ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ensemble_composition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensemble_composition',
    sa.Column('ensemble_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('composition_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['composition_id'], ['compositions.id'], name='ensemble_composition_ibfk_1'),
    sa.ForeignKeyConstraint(['ensemble_id'], ['ensembles.id'], name='ensemble_composition_ibfk_2'),
    sa.PrimaryKeyConstraint('ensemble_id', 'composition_id')
    )
    # ### end Alembic commands ###
