"""StudentStatus added

Revision ID: 112b54d36d7f
Revises: 0d70e0002a0b
Create Date: 2024-10-15 20:09:26.890884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112b54d36d7f'
down_revision = '0d70e0002a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('student_status_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'student_status', ['student_status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('student_status_id')
        batch_op.drop_column('active')

    op.drop_table('student_status')
    # ### end Alembic commands ###
