"""empty message

Revision ID: 23cf5ce33277
Revises: d02fd631b6e4
Create Date: 2024-10-19 09:31:40.582679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23cf5ce33277'
down_revision = 'd02fd631b6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_positions', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
