"""empty message

Revision ID: 34bac735eced
Revises: 23cf5ce33277
Create Date: 2024-10-21 20:21:11.577070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34bac735eced'
down_revision = '23cf5ce33277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.drop_column('started')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('created')

    # ### end Alembic commands ###
