"""empty message

Revision ID: 35598ce841e2
Revises: 83a73e62b9fb
Create Date: 2024-10-17 22:20:31.501266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35598ce841e2'
down_revision = '83a73e62b9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('student_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_assignments', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
