"""empty message

Revision ID: 3cfcd6b2d83f
Revises: ff81b8264c6d
Create Date: 2024-10-18 20:46:05.633212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cfcd6b2d83f'
down_revision = 'ff81b8264c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_assignments', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
