"""empty message

Revision ID: 454acd557bab
Revises: 09ed484f2268
Create Date: 2024-11-02 20:56:22.152728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454acd557bab'
down_revision = '09ed484f2268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
