"""empty message

Revision ID: 51ab15e5cf73
Revises: 79673045f29b
Create Date: 2024-10-17 22:47:00.682913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ab15e5cf73'
down_revision = '79673045f29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensemble_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ensemble_id', sa.Integer(), nullable=False),
    sa.Column('composition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composition_id'], ['compositions.id'], ),
    sa.ForeignKeyConstraint(['ensemble_id'], ['ensembles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ensemble_assignments')
    # ### end Alembic commands ###
