"""empty message

Revision ID: 5272575952ec
Revises: f79bc2ca611a
Create Date: 2024-10-27 20:21:56.270287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5272575952ec'
down_revision = 'f79bc2ca611a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'])
        batch_op.drop_column('ended')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
