"""empty message

Revision ID: 56044434a6de
Revises: 7b85dd54c9bd
Create Date: 2024-10-24 23:37:51.969397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56044434a6de'
down_revision = '7b85dd54c9bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_class_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_class_assignments', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
