"""empty message

Revision ID: 6072092c22ea
Revises: 1e61538af45a
Create Date: 2024-10-14 10:06:01.454321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6072092c22ea'
down_revision = '1e61538af45a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.alter_column('composition_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('composition_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
