"""empty message

Revision ID: 624e8a39db62
Revises: 95a8b1ab62be
Create Date: 2024-10-14 00:21:32.175074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624e8a39db62'
down_revision = '95a8b1ab62be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
