"""empty message

Revision ID: 66a56b7ba400
Revises: cc95558a1bc2
Create Date: 2025-01-08 23:26:25.750467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a56b7ba400'
down_revision = 'cc95558a1bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('enabled_modules')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled_modules', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
