"""Composer nationality relationship

Revision ID: 6b4a5a10cc33
Revises: ed89d290eefc
Create Date: 2024-10-16 08:09:31.435827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b4a5a10cc33'
down_revision = 'ed89d290eefc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'nationalities', ['nationality_id'], ['id'])
        batch_op.drop_column('nationality')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('nationality_id')

    # ### end Alembic commands ###
