"""empty message

Revision ID: 7844e05a4b0d
Revises: b22ac313d534
Create Date: 2024-10-16 15:58:32.103842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7844e05a4b0d'
down_revision = 'b22ac313d534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composition_player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composition_player', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
