"""empty message

Revision ID: 79673045f29b
Revises: 35598ce841e2
Create Date: 2024-10-17 22:32:43.276709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79673045f29b'
down_revision = '35598ce841e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('suffix', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('instrument_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'instrument', ['instrument_id'], ['id'])
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('instrument_id')
        batch_op.drop_column('suffix')
        batch_op.drop_column('prefix')

    # ### end Alembic commands ###
