"""empty message

Revision ID: 83a73e62b9fb
Revises: d1caede6e396
Create Date: 2024-10-17 21:29:35.917230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83a73e62b9fb'
down_revision = 'd1caede6e396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ensemble_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('started_on', sa.DateTime(), nullable=True),
    sa.Column('ended_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ensemble_id'], ['ensembles.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_assignment_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('ensemble_players_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'student_assignments', ['student_assignment_id'], ['id'])
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ensemble_players_ibfk_3', 'students', ['student_id'], ['id'])
        batch_op.drop_column('student_assignment_id')

    op.drop_table('student_assignments')
    # ### end Alembic commands ###
