"""empty message

Revision ID: 86075fa3d584
Revises: 96922eec39df
Create Date: 2024-10-17 12:39:59.309411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86075fa3d584'
down_revision = '96922eec39df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensemble_teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ensemble_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('assignment_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['ensemble_id'], ['ensembles.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.drop_constraint('ensembles_ibfk_2', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('ensembles_ibfk_2', 'teachers', ['teacher_id'], ['id'])

    op.drop_table('ensemble_teachers')
    # ### end Alembic commands ###
