"""empty message

Revision ID: 95a8b1ab62be
Revises: b61fa777ef95
Create Date: 2024-10-14 00:19:21.215339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a8b1ab62be'
down_revision = 'b61fa777ef95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensembles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('composition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composition_id'], ['compositions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ensemble_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ensemble_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ensemble_id'], ['ensembles.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ensemble_players')
    op.drop_table('ensembles')
    # ### end Alembic commands ###
