"""empty message

Revision ID: 95b2c70dfdaa
Revises: 0d2b46bb97ea
Create Date: 2024-10-18 21:30:08.649231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95b2c70dfdaa'
down_revision = '0d2b46bb97ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ended', sa.DateTime(), nullable=True))
        batch_op.drop_column('started_on')
        batch_op.drop_column('ended_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_on', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('started_on', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('ended')
        batch_op.drop_column('started')

    # ### end Alembic commands ###
