"""empty message

Revision ID: 96922eec39df
Revises: 7844e05a4b0d
Create Date: 2024-10-16 18:37:59.555380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96922eec39df'
down_revision = '7844e05a4b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composition_player', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('composition_player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
