"""empty message

Revision ID: 981c76f06710
Revises: a05ab22185bf
Create Date: 2024-10-17 23:44:35.786810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981c76f06710'
down_revision = 'a05ab22185bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shortcut', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.drop_column('shortcut')

    # ### end Alembic commands ###
