"""empty message

Revision ID: a05ab22185bf
Revises: 51ab15e5cf73
Create Date: 2024-10-17 23:22:51.911382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a05ab22185bf'
down_revision = '51ab15e5cf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.drop_constraint('instrument_ibfk_1', type_='foreignkey')
        batch_op.drop_column('main_instrument_id')
        batch_op.drop_column('is_obligatory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_obligatory', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('main_instrument_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('instrument_ibfk_1', 'instrument', ['main_instrument_id'], ['id'])

    # ### end Alembic commands ###
