"""empty message

Revision ID: b1420cbb9deb
Revises: 112b54d36d7f
Create Date: 2024-10-15 20:11:19.064069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1420cbb9deb'
down_revision = '112b54d36d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shortcut', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_status', schema=None) as batch_op:
        batch_op.drop_column('shortcut')

    # ### end Alembic commands ###
