"""empty message

Revision ID: b2cb4f5a53b0
Revises: 454acd557bab
Create Date: 2025-01-07 18:14:27.724781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cb4f5a53b0'
down_revision = '454acd557bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled_modules', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('enabled_modules')

    # ### end Alembic commands ###
