"""empty message

Revision ID: b61e2b2aa4ed
Revises: 34bac735eced
Create Date: 2024-10-22 20:21:08.333427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61e2b2aa4ed'
down_revision = '34bac735eced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour_donation', sa.Integer(), nullable=True))

    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour_donation', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.drop_column('hour_donation')

    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.drop_column('hour_donation')

    # ### end Alembic commands ###
