"""empty message

Revision ID: c862489d7ea9
Revises: 3cfcd6b2d83f
Create Date: 2024-10-18 21:14:59.778995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c862489d7ea9'
down_revision = '3cfcd6b2d83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ended', sa.DateTime(), nullable=True))

    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ended', sa.DateTime(), nullable=True))

    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ended', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('student_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ended', sa.DateTime(), nullable=True))
        batch_op.drop_column('ended_on')
        batch_op.drop_column('started_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_on', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('ended_on', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('ended')
        batch_op.drop_column('created')

    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('ended')
        batch_op.drop_column('created')

    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.drop_column('ended')
        batch_op.drop_column('created')

    with op.batch_alter_table('ensemble_assignments', schema=None) as batch_op:
        batch_op.drop_column('ended')
        batch_op.drop_column('created')

    # ### end Alembic commands ###
