"""empty message

Revision ID: d02fd631b6e4
Revises: fbec29ebf3a7
Create Date: 2024-10-19 09:30:08.618112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02fd631b6e4'
down_revision = 'fbec29ebf3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('shortcut', sa.String(length=100), nullable=False),
    sa.Column('full_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_position_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'academic_positions', ['academic_position_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('academic_position_id')

    op.drop_table('academic_positions')
    # ### end Alembic commands ###
