"""empty message

Revision ID: d1caede6e396
Revises: 
Create Date: 2024-10-17 21:21:20.497421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1caede6e396'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instruments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('order', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('is_obligatory', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('main_instrument_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['main_instrument_id'], ['instruments.id'], name='instruments_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
