"""empty message

Revision ID: dc9d915b7173
Revises: ee23d5855384
Create Date: 2024-10-14 21:13:06.936590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc9d915b7173'
down_revision = 'ee23d5855384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.alter_column('instrument_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.alter_column('instrument_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
