"""empty message

Revision ID: ee23d5855384
Revises: 6072092c22ea
Create Date: 2024-10-14 21:10:38.946363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee23d5855384'
down_revision = '6072092c22ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
