"""empty message

Revision ID: fbec29ebf3a7
Revises: 95b2c70dfdaa
Create Date: 2024-10-18 23:02:47.120800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbec29ebf3a7'
down_revision = '95b2c70dfdaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compositions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_link', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compositions', schema=None) as batch_op:
        batch_op.drop_column('youtube_link')

    # ### end Alembic commands ###
