"""empty message

Revision ID: ff81b8264c6d
Revises: 
Create Date: 2024-10-18 12:27:48.338185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff81b8264c6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_assignments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ensemble_players', ['ensemble_player_id'], ['id'])
        batch_op.drop_column('ensemble_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ensemble_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
